# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: root
  CLOUD_SQL_DATABASE_NAME: my_DB
  CLOUD_SQL_CONNECTION_NAME: central-spot-371223:europe-west1:my-sql-project
# [END gae_python37_cloudsql_config]
