# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: postgres
  CLOUD_SQL_PASSWORD: root
  CLOUD_SQL_DATABASE_NAME: my_db
  CLOUD_SQL_CONNECTION_NAME: central-spot-371223:europe-west1:my-first-sql
# [END gae_python37_cloudsql_config]
