# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: root
  CLOUD_SQL_DATABASE_NAME: my_DB
  CLOUD_SQL_CONNECTION_NAME: p428530804436-drflc1@gcp-sa-cloud-sql.iam.gserviceaccount.com
# [END gae_python37_cloudsql_config]
